-- migrate:up
CREATE TABLE IF NOT EXISTS book (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	description TEXT,

	addtional_metadata JSON,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE file
ADD COLUMN hash VARCHAR(50) NOT NULL UNIQUE AFTER name,
ADD COLUMN book BIGINT UNSIGNED AFTER kind,
ADD CONSTRAINT file_ibfk_1 FOREIGN KEY (book) REFERENCES book(id);

-- migrate:down
ALTER TABLE file
DROP CONSTRAINT file_ibfk_1,
DROP COLUMN book,
DROP COLUMN hash;

DROP TABLE IF EXISTS book;
