-- migrate:up
CREATE TABLE IF NOT EXISTS file (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	name VARCHAR(255) NOT NULL UNIQUE,
	metadata JSON,
	kind ENUM('audiobook', 'ebook') NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE IF EXISTS file;
