-- migrate:up
CREATE TABLE IF NOT EXISTS book (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	description TEXT,

	metadata JSON,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS series (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	name VARCHAR(255) NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS series_book (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	book BIGINT UNSIGNED NOT NULL,
	series BIGINT UNSIGNED NOT NULL,
	book_no DECIMAL(6, 2) NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (book) REFERENCES book(id),
	FOREIGN KEY (series) REFERENCES series(id),

	UNIQUE (book, series),
	UNIQUE (series, book_no)
);

CREATE TABLE IF NOT EXISTS audiobook (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	book BIGINT UNSIGNED,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (book) REFERENCES book(id)
);

CREATE TABLE IF NOT EXISTS audio_file (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	name VARCHAR(255) NOT NUll,
	hash CHAR(40) NOT NULL,
	metadata JSON,

	audiobook BIGINT UNSIGNED,
	track_no INT,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (audiobook) REFERENCES audiobook(id),
	UNIQUE (track_no, audiobook)
);

CREATE TABLE IF NOT EXISTS ebook (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

	name VARCHAR(255) NOT NULL,
	hash CHAR(40) NOT NULL,
	metadata JSON,

	book BIGINT UNSIGNED,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE IF EXISTS ebook;
DROP TABLE IF EXISTS audio_file;
DROP TABLE IF EXISTS audiobook;
DROP TABLE IF EXISTS series_book;
DROP TABLE IF EXISTS series;
DROP TABLE IF EXISTS book;
