-- migrate:up
CREATE TABLE book (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,

	title VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,

	UNIQUE(title, author)
);

CREATE TABLE audiobook (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,

	book BIGINT NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (book) REFERENCES book(id)
);

CREATE TABLE file (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,

	name VARCHAR(255) NOT NULL,
	hash CHAR(40) NOT NULL UNIQUE,
	codec VARCHAR(50) NOT NULL,

	audiobook BIGINT,
	chapter INT,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (audiobook) REFERENCES audiobook(id)
);

-- migrate:down
DROP TABLE file;
DROP TABLE audiobook;
DROP TABLE book;
